### ISSUE TITLE
"containers" should be an array and not a dictionary

### ISSUE THREAD

**Issue by falfaro** [ksonnet/ksonnet-lib#13]
While using jsonnet Jsonnet commandline interpreter v0.9.3 built-in locally on my Ubuntu 16.04 LTS machine, I noticed that jsonnet plus ksonnet yield invalid JSON:

$ git clone https://github.com/ksonnet/ksonnet-lib
$ cd ksonnet-lib/examples/readme/
$ jsonnet hello-nginx.jsonnet > json
$ kubectl create -f json
error: error validating "json": error validating data: [found invalid field hostMappings for v1.PodSpec, expected type array, for field spec.template.spec.containers, got map]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by hausdorff** [comment]
Thanks for the report, this is fixed in the PR above.

The spec expects `containers` to be an array, and the example passes in a single `v1.Container` object. In the PR above we insert a runtime conditional that checks if the parameter is an array, and if it's not, it is boxed up as an array on behalf of the user.
