### ISSUE TITLE
Some API objects seem like exceptions to the `kind` blacklist rule

### ISSUE THREAD

**Issue by hausdorff** [ksonnet/ksonnet-lib#43]
Cursory examination seems to indicate that `rbac.v1alpha1.roleRef` has a `kind` field that is meant to refer to a different API group's `kind`, rather than its own. This would make it an exception to the `kind` blacklist rule.

**Comment by seh** [comment]
Note, though, that the "kinds" present are not API object kinds, at least in Kubernetes, because of [the three permitted for now](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/rbac/types.go#L66-L68), only "ServiceAccount" matches an existing object kind. Neither "User" nor "Group" are kinds of Kubernetes objects.
